Repository mju-likelion/12th-crossover-server-2, pull requests merged in 2024-06, with the labels that each got.

#4 feature:ERD_생성-#3
  crossover-server-2/build.gradle
  crossover-server-2/src/main/java/model/BaseEntity.java
  crossover-server-2/src/main/java/model/Board.java
  crossover-server-2/src/main/java/model/Clause.java
  crossover-server-2/src/main/java/model/Comment.java
  crossover-server-2/src/main/java/model/User.java
  crossover-server-2/src/main/java/model/UserClause.java
Labels: feature

#21 Feature/#19 패키지 구조 정리, 누락 사항 작성
  crossover-server-2/build.gradle
  crossover-server-2/src/main/java/org/example/crossoverserver2/CrossoverServer2Application.java
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/constant/RegexPatterns.java
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/controller/AuthController.java
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/controller/BoardController.java
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/controller/CommentController.java
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/dto/ResponseDto.java
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/dto/request/auth/SignUpRequestData.java
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/dto/request/board/WriteBoardDto.java
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/dto/request/comment/WriteCommentDto.java
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/exception/errorcode/ErrorCode.java
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/model/Board.java
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/repository/UserRepository.java
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/service/BoardService.java
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/service/CommentService.java
  crossover-server-2/src/test/java/org/example/crossoverserver2/planeletter/controller/AuthControllerTest.java
  crossover-server-2/src/test/java/org/example/crossoverserver2/planeletter/dto/request/auth/SignUpRequestDataTest.java
Labels: bug, enhancement, refactor

#29 Feature/#28 댓글 페이지네이션 구현, 페이지 예외 처리 추가
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/controller/CommentController.java
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/dto/request/auth/LoginRequestData.java
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/dto/response/PaginationDto.java
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/dto/response/board/BoardListResponseData.java
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/dto/response/comment/CommentListResponseData.java
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/exception/advice/ExceptionController.java
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/exception/errorcode/ErrorCode.java
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/repository/CommentRepository.java
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/service/BoardService.java
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/service/CommentService.java
Labels: enhancement, feature

#31 Feature/#30 에러코드 및 예외 처리 수정
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/exception/AlreadyExistException.java
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/exception/advice/ExceptionController.java
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/exception/errorcode/ErrorCode.java
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/service/CommentService.java
Labels: refactor

#35 Feature/#34로그아웃 기능 수정 및 구조 변경
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/controller/AuthController.java
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/controller/UserController.java
Labels: refactor

#40 Feature/#39 AuthController 쿠키 수정
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/config/CorsConfig.java
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/controller/AuthController.java
Labels: feature, refactor

#45 Feature/#43 로그아웃 시 토큰 삭제 기능 리팩토링
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/controller/AuthController.java
Labels: enhancement

#50 Feature/# 49 로그인 Validation 기능 추가
  crossover-server-2/src/main/java/org/example/crossoverserver2/planeletter/dto/request/auth/LoginRequestData.java
Labels: enhancement
